import './globals.css';
import 'react-quill/dist/quill.snow.css';
import { Inter } from 'next/font/google'
import Palette from './Provider/themeProvider'
import AppMenuBar from './components/NavBar/AppMenuBar'
const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {

 
  return (
    <html lang="en">
      <body className={inter.className}>
        <Palette>
          {children}
        </Palette>
      </body>
    </html>
  )
}
